name: introduction_plasma_2026
# d'après github.com/CVandiedonck/introduction_plasma.git
# avec ajouts depuis github.com/Scaburet/MEG-M1-A2B-2026

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
# defaults changé en nodefaults pour construire l'env sur Mydocker de Saclay, janvier 2025
  - conda-forge
  - bioconda
  - nodefaults
  
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook>=7,<8
  - jupyter_server>=2,<3
  - jupyter-server-proxy>=4.1,<4.2
  - jupyter-resource-usage
  - jupyterlab-topbar-text    # affiche le nom de l'environnement à droite dans la topbar
  - nodejs
  - nbresuse
  - libgomp

  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # JupyterLab git
  # https://github.com/jupyterlab/jupyterlab-git
  - jupyterlab-git
  # JupyterLab Variable inspector
  # https://github.com/lckr/jupyterlab-variableInspector
  - jupyterlab-variableinspector


  # Build tools required for Ubuntu 24.04
  - gxx_linux-64
  - gcc_linux-64
  - gfortran_linux-64

  # Bash environment
  - bash_kernel

  # Python environment
  - python>=3.10
  - pip
  - ipywidgets>=8,<9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - biopython
  
  # R environment (version for Ubuntu 24.04)
  - r-irkernel
  - r-base>=4

  # R packages for the M1 A2B course:
  - r-essentials   
  - r-tidyverse
  - r-repr
  - r-biocManager  

  - pip:
  # Print module version
    - watermark

